# Generated by Django 4.1.9 on 2023-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_delete_student_remove_mydata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='serial',
            field=models.IntegerField(),
        ),
    ]
