# Generated by Django 4.1.9 on 2023-06-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_mydata_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
