# Generated by Django 4.1.9 on 2023-06-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_mydata_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydata',
            name='serial',
            field=models.CharField(default='error', max_length=100),
        ),
    ]
