# Generated by Django 4.1.9 on 2023-06-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_mydata_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='name',
            new_name='pid',
        ),
    ]
